containers:
  - '{defaults/container/*,environments/*/overrides/container/*}'
non_containers:
  - '{.github,defaults,environments,infrastructure}/**'
  - '!{defaults/container/*,environments/*/overrides/container/*}'
dev_envs:
  - 'environments/*/environment_dev.yml'
stable_envs:
  - 'environments/**'
  - '!{environments/*/environment_dev.yml,environments/*/overrides/container/container.def}'
non_envs:
  - '{.github,defaults,infrastructure}/**'
  - '!defaults/container/*'