name: Build container images
on:
  push:
    branches:
      - main
    paths:
      - '**/container/container.def'
  workflow_dispatch:
    inputs:
        targets:
            description: |
              Comma-separated list of container definition files to build.
              E.g. "defaults/container/container.def,myenv/overrides/container/container.def".
            required: True

jobs:
  get-container-def-targets:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.resolve-targets.outputs.targets }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
    
      - name: Determine which container definition files to build
        id: resolve-targets
        run: |
          if [[ '${{ github.event_name }}' == workflow_dispatch ]]; then
            targets='${{ inputs.targets }}'
            # Check that all targets exist
            while IFS=, read -r target; do
              [ -z "$target" ] && continue
              if [ ! -f "$target" ]; then
                echo "::error::The specified container definition '$target' does not exist."
                exit 1
              fi
            done <<< '${{ inputs.targets }},'
            echo "Building the following 'container definition' files:"
            echo "$targets" | tr ',' '\n'
          else
            targets=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- '**/container/container.def')
            echo "Building the following changed container definition files:"
            echo "$targets"
            targets=$(echo -n "$targets" | tr '\n' ',')
          fi
          # Join all targets with a comma and set it as an output variable
          echo "targets=$targets" >> "$GITHUB_OUTPUT"

  build-images:
    runs-on: ubuntu-latest
    needs: get-container-def-targets
    if: needs.get-container-def-targets.outputs.targets != ''
    container:
      image: quay.io/singularity/singularity:v4.3.1
    env:
      CONTAINER_IMAGE_NAME: base_image.sif
      TARGETS: ${{ needs.get-container-def-targets.outputs.targets }}
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.REPO_CONTENT_WRITE_TOKEN }}
    
      - name: Build singularity images
        shell: bash
        run: |
          while IFS=, read -r target; do
            [ -z "$target" ] && continue
            container_image="$(dirname "$target")/${{ env.CONTAINER_IMAGE_NAME }}"
            echo "Building container definition '$target' into image '$container_image'..."
            singularity --verbose build --force "$container_image" "$target"
          done <<< '${{ env.TARGETS }},'
    
      # Since we run this entire job in a container, it runs as root by default. 
      # This makes all files created in the container owned by root, which causes issues when we
      # try to commit and push the updated container image back to the repository.
      # For this reason, we need to change the ownership of the current directory
      # from root to user before we can commit and push it.
      - name: Change ownership
        run: sudo chown -R $(id -u):$(id -g) .

      - name: Commit and push updated container image
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add '**/container/${{ env.CONTAINER_IMAGE_NAME }}'
          git commit -m "Updated built container images ${{ env.TARGETS }}." \
            -m "This commit was automatically generated by the '${{ github.workflow }}' GitHub workflow."
          git push