name: Closed PR
description: |
  This workflow triggers whenever a PR is closed, and performs the following tasks:
  
  - All the STAGING environments that were deployed from the PR are deleted

  - If the Pull Request is merged and the changes involved any development environment spec file
    (`environments/*/environment_dev.yml`), for each environment changed (with the exception of
    the vars.TEST_ENV environment), a DEVELOPMENT environment is deployed to PRODUCTION

on:
  pull_request:
    types: [closed]
    branches: [main]

env:
  TEST_ENV: ${{ vars.TEST_ENV }}

jobs:
  # In general, this workflow should always be "in sync" with the `deploy_env.yml` workflow.
  # This means that for the env deletion and deployment to DEVELOPMENT PRODUCTION, this
  # workflow should follow the same logic that is used in the `deploy_env.yml` workflow to detect
  # and deploy the STAGING environments.
  # For this reason, we run the parse_changed_files job identically to how we do in the `deploy_env.yml`
  # workflow, to make sure that we are detecting the same changes
  parse_changed_files:
    name: Parse changed files
    runs-on: ubuntu-latest
    outputs:
      containers: ${{ steps.changed-files.outputs.containers }}
      dev_envs: ${{ steps.changed-files.outputs.dev_envs }}
      dev_envs_files: ${{ steps.changed-files.outputs.dev_envs_files }}
      stable_envs: ${{ steps.changed-files.outputs.stable_envs }}
      stable_envs_files: ${{ steps.changed-files.outputs.stable_envs_files }}
      non_envs: ${{ steps.changed-files.outputs.non_envs }}
      non_containers: ${{ steps.changed-files.outputs.non_containers }}
    steps:
      - uses: actions/checkout@v6

      - name: Parse changed files
        id: changed-files
        uses: ./.github/actions/parse_changed_files

  get-environments:
    name: Get environments
    runs-on: ubuntu-latest
    needs: [parse_changed_files]
    outputs:
      envs_to_delete: ${{ steps.get-environments.outputs.envs_to_delete }}
      envs_to_deploy: ${{ steps.get-environments.outputs.envs_to_deploy }}
    env:
      DEV_ENVS_FILES: ${{ needs.parse_changed_files.outputs.dev_envs_files }}
      STABLE_ENVS_FILES: ${{ needs.parse_changed_files.outputs.stable_envs_files }}
      NON_ENVS: ${{ needs.parse_changed_files.outputs.non_envs }}
    steps:
      - name: Get changed environments
        id: get-environments
        run: |
          # The environments to delete are both the DEVELOPMENT and STABLE environments
          # Get DEVELOPMENT environments
          dev_envs=$(
            echo "$DEV_ENVS_FILES" | jq -c '[.[] | split("/")[1]] | unique'
          )
          # Get STABLE environments
          stable_envs=$(
            echo "$STABLE_ENVS_FILES" | jq -c '[.[] | split("/")[1]] | unique'
          )
          # Add them together
          envs_to_delete=$(
            jq -n --argjson a "$dev_envs" --argjson b "$stable_envs" '$a + $b | unique'
          )
          # If there are changes that don't involve the `environments` folder,
          # add a vars.TEST_ENV environment to the environments to delete
          if [[ $NON_ENVS == true ]]; then
            envs_to_delete=$(
              echo "$envs_to_delete" | jq -c '. + ["${{ vars.TEST_ENV }}"] | unique'
            )
          fi
          # The environments to deploy are the DEVELOPMENT environments without the vars.TEST_ENV environment
          envs_to_deploy=$(
            echo "$dev_envs" | jq 'map(select(. != "${{ vars.TEST_ENV }}"))'
          )
          echo "envs_to_deploy=$envs_to_deploy" >> $GITHUB_OUTPUT
          echo "envs_to_delete=$envs_to_delete" >> $GITHUB_OUTPUT

  set_version:
    name: Set version
    runs-on: ubuntu-latest
    needs: get-environments
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    # Only run if there are envs to deploy
    if: needs.get-environments.outputs.envs_to_deploy != '[]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set version
        id: set-version
        uses: ./.github/actions/set_version
        with:
          is_stable: false
  
  deploy_development_production:
    name: Deploy DEVELOPMENT ${{ matrix.environment }} environment to PRODUCTION
    needs: [get-environments, set_version]
    # Only run if the PR was merged (not closed without merging)
    if: needs.get-environments.outputs.envs_to_deploy != '[]' && github.event.pull_request.merged == true
    strategy:
      matrix:
        environment: ${{ fromJson(needs.get-environments.outputs.envs_to_deploy) }}
    uses: ./.github/workflows/deploy_env.yml
    with:
      environment: "${{ matrix.environment }}"
      version: "${{ needs.set_version.outputs.version }}"
      staging: true
      production: true
      is_stable: false
    secrets: inherit
  
  delete_staging_environments:
    name: Delete STAGING environments deployed from PR ${{ github.event.pull_request.number }}
    needs: [get-environments]
    if: needs.get-environments.outputs.envs_to_delete != '[]'
    strategy:
      matrix:
        environment: ${{ fromJson(needs.get-environments.outputs.envs_to_delete) }}
    uses: ./.github/workflows/deploy_env.yml
    with:
      environment: "${{ matrix.environment }}"
      staging: false
      production: false
    secrets: inherit