name: Deploy envs to STAGING
description: |
  This workflow deploys environments to STAGING for Pull Requests opened to this repo 
  (with `main` as a base) in the following cases: 
  
  - If the changes involve the `environments` folder, for each environment subfolder changed:

    - If the changes involve the `environment_dev.yml`, a DEVELOPMENT environment
      is deployed to STAGING (even if there are also changes to the `environment.yml`)
    - If the changes don't involve the `environment_dev.yml`, a STABLE environment
      is deployed to STAGING

  - If the changes don't involve the `environments` folder (for example any change to the 
    `defaults` folder), a STABLE 'test' environment is deployed to STAGING.
    We use the 'test' environment as a test case only for infrastuture automatic testing in CI

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]
    paths-ignore: ['.github/**']

env:
  TEST_ENV: ${{ vars.TEST_ENV }}
  COMMENT_LABEL: 'deployment-${{ github.sha }}'

jobs:
  sanity_checks:
    name: Sanity checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      # Since we have the built container images within the repos, and we automatically build them
      # whenever there is a change to a container definition file, we need to make sure that, if this
      # workflow is triggered by a pull request, no changes to a container definition or built image
      # are found, otherwise we might end up deploying an environment using a different container that
      # the one we are supposed to be testing and deploying. 
      - name: Sanity check on container-related files
        run: |
          container_files=$(
            git diff --name-only \
              ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }} -- \
              '**/container/container.def' \
              '**/container/base_image.sif'
          )
          if [ -n "$container_files" ]; then
            # Format the list of changed container files for better readability in the error message
            # Using %0A for newlines to ensure the message is properly formatted in the GitHub Actions log
            formatted=$(echo "$container_files" | sed 's/^/  /' | tr '\n' '%0A')
            msg="Changes to container definition files detected.%0A${formatted}%0A%0A"
            msg+="To change container-related files, open a separate pull request only with those changes."
            echo "::error::${msg}"
            exit 1
          fi
  
  get-date:
    name: Get current date
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.get-date.outputs.date }}
    steps:
      - name: Get date
        id: get-date
        run: |
          date=$(TZ='Australia/Sydney' date '+%FT%T %Z')
          echo "date=$date" >> "$GITHUB_OUTPUT"

  get-changed-environments:
    name: Get changed environments
    runs-on: ubuntu-latest
    outputs:
      dev_envs: ${{ steps.changed.outputs.dev_envs }}
      stable_envs: ${{ steps.changed.outputs.stable_envs }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get changed environments
        id: changed
        run: |
          env_changes=$(
            git diff --name-only \
              ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }} -- \
              environments/
          )
          
          dev_envs=[]
          stable_envs=[]

          if [ -z "$env_changes" ]; then
            # No changes in the `environments` folder. 
            # Deploy a STABLE TEST_ENV environment in STAGING
            stable_envs=$(jq -cn --arg e ${{ env.TEST_ENV }} '[$e]')
          else
            # Get unique environment names that changed
            envs=$(
              echo "$env_changes" \
              | cut -d'/' -f2 \
              | sort -u \
            )
            for env in $envs; do
              if echo "$env_changes" | grep -q "^environments/$env/environment_dev.yml"; then
                dev_envs=$(echo "$dev_envs" | jq -c --arg e "$env" '. += [$e]')
              else
                stable_envs=$(echo "$stable_envs" | jq -c --arg e "$env" '. += [$e]')
              fi
            done
          fi
          echo "dev_envs=$dev_envs" >> $GITHUB_OUTPUT
          echo "stable_envs=$stable_envs" >> $GITHUB_OUTPUT

  set_version_dev:
    name: Set version for DEVELOPMENT environments
    runs-on: ubuntu-latest
    needs: get-changed-environments
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    # Only run if there are envs to deploy
    if: needs.get-changed-environments.outputs.dev_envs != '[]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set version
        id: set-version
        uses: ./.github/actions/set_version
        with:
          is_stable: false
  
  set_version_stable:
    name: Set version for STABLE environments
    runs-on: ubuntu-latest
    needs: get-changed-environments
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    # Only run if there are envs to deploy
    if: needs.get-changed-environments.outputs.stable_envs != '[]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set version
        id: set-version
        uses: ./.github/actions/set_version
        with:
          is_stable: true

  deploy_development_staging:
    name: Deploy DEVELOPMENT ${{ matrix.environment }} environment to STAGING
    needs: [sanity_checks, get-changed-environments, set_version_dev]
    strategy:
      matrix:
        environment: ${{ fromJson(needs.get-changed-environments.outputs.dev_envs) }}
    uses: ./.github/workflows/deploy_env.yml
    with:
      environment: "${{ matrix.environment }}"
      # We prepend `dev-` to the version of a DEVELOPMENT environment
      version: "${{ needs.set_version_dev.outputs.version }}"
      staging: true
      production: false
      is_stable: false
    secrets: inherit
  
  deploy_stable_staging:
    name: Deploy STABLE ${{ matrix.environment }} environment to STAGING
    needs: [sanity_checks, get-changed-environments, set_version_stable]
    strategy:
      matrix:
        environment: ${{ fromJson(needs.get-changed-environments.outputs.stable_envs) }}
    uses: ./.github/workflows/deploy_env.yml
    with:
      environment: "${{ matrix.environment }}"
      version: "${{ needs.set_version_stable.outputs.version }}"
      staging: true
      production: false
      is_stable: true
    secrets: inherit

  initialise_pr_comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    needs: 
      - sanity_checks
      - get-changed-environments
      - set_version_dev
      - set_version_stable
    # Run if neither of the needed job failed but run if any was skipped
    if: always() && !failure() && !cancelled()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Create pr_init_info JSON
        id: create-pr-init-info
        uses: ./.github/actions/create_pr_init_info_json

      - name: Set pr-init message
        id: set-pr-init-message
        uses: ./.github/actions/set_message
        with:
          message-type: pr-init
          data-file: "${{ steps.create-pr-init-info.outputs.output-file }}"

      - name: Comment on PR with deployment information
        uses: access-nri/actions/.github/actions/comment@davide/add-message-file
        with:
          message-file: "${{ steps.set-pr-init-message.outputs.message-file-path }}"
          label: ${{ env.COMMENT_LABEL }}
    
      - name: Upload pr-init-info JSON as artifact
        uses: actions/upload-artifact@v7
        with:
          path: "${{ steps.create-pr-init-info.outputs.output-file }}"
          name: pr-init-info
  
  update_pr_comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    needs: [get-date, deploy_development_staging, deploy_stable_staging]
    # Run also if any needed job failed or was skipped
    if: always() && !cancelled()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download all hpc target deployment info artifacts
        uses: actions/download-artifact@v8
        id: download-artifacts
        with:
          pattern: deployment_*
          merge-multiple: true
          path: downloaded_artifacts
      
      - name: Create all_deployments_info JSON
        id: create-all-deployments-info
        uses: ./.github/actions/create_all_deployments_info_json
        with:
          started-at: "${{ needs.get-date.outputs.date }}"
          hpc-target-deployment-info-json-dir: "${{ steps.download-artifacts.outputs.download-path }}"

      - name: Set PR message
        id: set-pr-message
        uses: ./.github/actions/set_message
        with:
          message-type: pr-update
          data-file: "${{ steps.create-all-deployments-info.outputs.output-file }}"

      - name: Comment on PR with deployment information
        uses: access-nri/actions/.github/actions/comment@davide/add-message-file
        with:
          message-file: "${{ steps.set-pr-message.outputs.message-file-path }}"
          label: ${{ env.COMMENT_LABEL }}
    
      - name: Upload all_deployments_info JSON as artifact
        uses: actions/upload-artifact@v7
        with:
          path: "${{ steps.create-all-deployments-info.outputs.output-file }}"
          name: all_deployments_info
  
  update_pr_when_cancelled:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    needs: [get-date, initialise_pr_comment, deploy_development_staging, deploy_stable_staging]
    # Run if the workflow was cancelled
    # And only if initialise_pr_comment is successful, otherwise we won't have the pr_init_info artifact
    if: cancelled() && needs.initialise_pr_comment.result == 'success'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download pr-init-info JSON as artifact
        id: download-pr-init-info
        uses: actions/download-artifact@v8

      - name: Set PR message
        id: set-pr-message
        uses: ./.github/actions/set_message
        with:
          message-type: pr-cancelled
          data-file: "${{ steps.download-pr-init-info.outputs.download-path }}/pr_init_info.json"

      - name: Comment on PR with deployment information
        uses: access-nri/actions/.github/actions/comment@davide/add-message-file
        with:
          message-file: "${{ steps.set-pr-message.outputs.message-file-path }}"
          label: ${{ env.COMMENT_LABEL }}