name: Deploy envs to STAGING
description: |
  This workflow deploys environments to STAGING for Pull Requests opened to this repo 
  (with `main` as a base) in the following cases: 
  
  - If the changes involve the `environments` folder, for each environment subfolder changed:

    - If the changes involve the `environment_dev.yml` (but not the `environment.yml`),
      a DEVELOPMENT environment is deployed to STAGING
    - If the changes involve the `environment.yml` (but not the `environment_dev.yml`),
      a STABLE environment is deployed to STAGING
    - If the changes involve both the `environment_dev.yml` and `environment.yml`,
      both a STABLE and DEVELOPMENT environment is deployed to STAGING
    - If the changes don't involve either of the environment spec files (e.g., changes in an override file)
      a STABLE environment is deployed to STAGING

  - If the changes don't involve the `environments` folder (for example any change to the
    `defaults` folder), a STABLE 'test' environment is deployed to STAGING.
    We use the 'test' environment as an example for infrastuture automatic testing within CI

on:
  pull_request:
    types: [opened, synchronize]
    branches: main

env:
  TEST_ENV: ${{ vars.TEST_ENV }}
  COMMENT_LABEL: 'deployment-${{ github.sha }}'

jobs:
  parse_changed_files:
    name: Parse changed files
    runs-on: ubuntu-latest
    outputs:
      containers: ${{ steps.changed-files.outputs.containers }}
      dev_envs: ${{ steps.changed-files.outputs.dev_envs }}
      dev_envs_files: ${{ steps.changed-files.outputs.dev_envs_files }}
      stable_envs: ${{ steps.changed-files.outputs.stable_envs }}
      stable_envs_files: ${{ steps.changed-files.outputs.stable_envs_files }}
      non_envs: ${{ steps.changed-files.outputs.non_envs }}
      non_containers: ${{ steps.changed-files.outputs.non_containers }}
    steps:
      - uses: actions/checkout@v6

      - name: Parse changed files
        id: changed-files
        uses: ./.github/actions/parse_changed_files

  sanity_checks:
    name: Sanity checks
    runs-on: ubuntu-latest
    needs: parse_changed_files
    env:
      CONTAINERS_CHANGES: ${{ needs.parse_changed_files.outputs.containers }}
      NON_CONTAINERS_CHANGES: ${{ needs.parse_changed_files.outputs.non_containers }}
    steps:
      # Since we have the built container images within the repos, and we automatically build them
      # whenever there is a change to a container definition file, we need to make sure that, if this
      # workflow is triggered by a pull request, no changes to a container definition or built image
      # are found together with other changes, otherwise we might end up deploying an environment
      # using a different container to the one we are supposed to be testing and deploying.
      - name: Sanity check on container-related files
        run: |
          if [[ $CONTAINERS_CHANGES == 'true' && $NON_CONTAINERS_CHANGES == 'true' ]]; then
            echo "::error::Container definition changes must be submitted in an isolated pull request,"\
              "with no other changes. Please open a separate PR for container-related files."
            exit 1
          fi
  
  get-date:
    name: Get current date
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.get-date.outputs.date }}
    steps:
      - name: Get date
        id: get-date
        run: |
          date=$(TZ='Australia/Sydney' date '+%FT%T %Z')
          echo "date=$date" >> "$GITHUB_OUTPUT"

  get-environments:
    name: Get environments
    runs-on: ubuntu-latest
    needs: [parse_changed_files, sanity_checks]
    outputs:
      dev_envs: ${{ steps.get-environments.outputs.dev_envs }}
      stable_envs: ${{ steps.get-environments.outputs.stable_envs }}
    env:
      DEV_ENVS_FILES: ${{ needs.parse_changed_files.outputs.dev_envs_files }}
      STABLE_ENVS_FILES: ${{ needs.parse_changed_files.outputs.stable_envs_files }}
      NON_ENVS: ${{ needs.parse_changed_files.outputs.non_envs }}
    steps:
      - name: Get changed environments
        id: get-environments
        run: |
          # Get DEVELOPMENT environments
          dev_envs=$(
            echo "$DEV_ENVS_FILES" | jq -c '[.[] | split("/")[1]] | unique'
          )
          # Get STABLE environments
          stable_envs=$(
            echo "$STABLE_ENVS_FILES" | jq -c '[.[] | split("/")[1]] | unique'
          )
          # If there are changes that don't involve the `environments` folder,
          # add a vars.TEST_ENV environment to the STABLE ones
          if [[ $NON_ENVS == true ]]; then
            stable_envs=$(
              echo "$stable_envs" | jq -c '. + ["${{ vars.TEST_ENV }}"] | unique'
            )
          fi
          echo "dev_envs=$dev_envs" >> $GITHUB_OUTPUT
          echo "stable_envs=$stable_envs" >> $GITHUB_OUTPUT

  set_version_dev:
    name: Set version for DEVELOPMENT environments
    runs-on: ubuntu-latest
    needs: get-environments
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    # Only run if there are envs to deploy
    if: needs.get-environments.outputs.dev_envs != '[]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set version
        id: set-version
        uses: ./.github/actions/set_version
        with:
          is_stable: false
  
  set_version_stable:
    name: Set version for STABLE environments
    runs-on: ubuntu-latest
    needs: get-environments
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    # Only run if there are envs to deploy
    if: needs.get-environments.outputs.stable_envs != '[]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set version
        id: set-version
        uses: ./.github/actions/set_version
        with:
          is_stable: true

  deploy_development_staging:
    name: Deploy DEVELOPMENT ${{ matrix.environment }} environment to STAGING
    needs: [get-environments, set_version_dev]
    strategy:
      matrix:
        environment: ${{ fromJson(needs.get-environments.outputs.dev_envs) }}
    uses: ./.github/workflows/deploy_env.yml
    with:
      environment: "${{ matrix.environment }}"
      # We prepend `dev-` to the version of a DEVELOPMENT environment
      version: "${{ needs.set_version_dev.outputs.version }}"
      staging: true
      production: false
      is_stable: false
    secrets: inherit
  
  deploy_stable_staging:
    name: Deploy STABLE ${{ matrix.environment }} environment to STAGING
    needs: [get-environments, set_version_stable]
    strategy:
      matrix:
        environment: ${{ fromJson(needs.get-environments.outputs.stable_envs) }}
    uses: ./.github/workflows/deploy_env.yml
    with:
      environment: "${{ matrix.environment }}"
      version: "${{ needs.set_version_stable.outputs.version }}"
      staging: true
      production: false
      is_stable: true
    secrets: inherit

  initialise_pr_comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    needs: [set_version_dev,set_version_stable]
    # Run if at least one of set_version_dev or set_version_stable succeeded and neither failed
    if: always() && !failure() && !cancelled() && (needs.set_version_dev.result == 'success' || needs.set_version_stable.result == 'success')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Create pr_init_info JSON
        id: create-pr-init-info
        uses: ./.github/actions/create_pr_init_info_json

      - name: Set pr-init message
        id: set-pr-init-message
        uses: ./.github/actions/set_message
        with:
          message-type: pr-init
          data-file: "${{ steps.create-pr-init-info.outputs.output-file }}"

      - name: Comment on PR with deployment information
        uses: access-nri/actions/.github/actions/comment@davide/add-message-file
        with:
          message-file: "${{ steps.set-pr-init-message.outputs.message-file-path }}"
          label: ${{ env.COMMENT_LABEL }}
    
      - name: Upload pr-init-info JSON as artifact
        uses: actions/upload-artifact@v7
        with:
          path: "${{ steps.create-pr-init-info.outputs.output-file }}"
          name: pr-init-info
  
  update_pr_comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    needs: [get-date, deploy_development_staging, deploy_stable_staging, initialise_pr_comment]
    # Run if initialise_pr_comment is successful
    if: always() && !cancelled() && needs.initialise_pr_comment.result == 'success'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download all hpc target deployment info artifacts
        uses: actions/download-artifact@v8
        id: download-artifacts
        with:
          pattern: deployment_*
          merge-multiple: true
          path: downloaded_artifacts
      
      - name: Create all_deployments_info JSON
        id: create-all-deployments-info
        continue-on-error: true
        uses: ./.github/actions/create_all_deployments_info_json
        with:
          started-at: "${{ needs.get-date.outputs.date }}"
          hpc-target-deployment-info-json-dir: "${{ steps.download-artifacts.outputs.download-path }}"
    
      - name: Download pr-init-info JSON as artifact
        id: download-pr-init-info
        uses: actions/download-artifact@v8

      - name: Set PR message
        id: set-pr-message
        uses: ./.github/actions/set_message
        with:
          message-type: pr-update
          data-file: ${{ steps.create-all-deployments-info.outcome == 'success' && steps.create-all-deployments-info.outputs.output-file || format('{0}/pr_init_info.json', steps.download-pr-init-info.outputs.download-path) }}

      - name: Comment on PR with deployment information
        uses: access-nri/actions/.github/actions/comment@davide/add-message-file
        with:
          message-file: "${{ steps.set-pr-message.outputs.message-file-path }}"
          label: ${{ env.COMMENT_LABEL }}
    
      - name: Upload all_deployments_info JSON as artifact
        uses: actions/upload-artifact@v7
        if: steps.create-all-deployments-info.outcome == 'success'
        with:
          path: "${{ steps.create-all-deployments-info.outputs.output-file }}"
          name: all_deployments_info
  
  update_pr_when_cancelled:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    needs: [get-date, initialise_pr_comment, deploy_development_staging, deploy_stable_staging]
    # Run if the workflow was cancelled and initialise_pr_comment is successful
    if: cancelled() && needs.initialise_pr_comment.result == 'success'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download pr-init-info JSON as artifact
        id: download-pr-init-info
        uses: actions/download-artifact@v8

      - name: Set PR message
        id: set-pr-message
        uses: ./.github/actions/set_message
        with:
          message-type: pr-cancelled
          data-file: "${{ steps.download-pr-init-info.outputs.download-path }}/pr_init_info.json"

      - name: Comment on PR with deployment information
        uses: access-nri/actions/.github/actions/comment@davide/add-message-file
        with:
          message-file: "${{ steps.set-pr-message.outputs.message-file-path }}"
          label: ${{ env.COMMENT_LABEL }}